#!/usr/bin/env python3
#                                                                             #
#    Copyright (c) 2025 Ming Wen <wenm@umich.edu>, University of Michigan.    #
#                                                                             #
#    Functions used for generating intermediate quantities from GW            #
#    calculations.                                                            #
#                                                                             #

import numpy as np
import h5py
from scipy.linalg import inv

from irFT import IR_factory
import irFT

kB_ha_per_K = 3.16681e-6


def fermi(energy_minus_mu, beta):
    """Fermi-Dirac distribution function."""
    x = beta * energy_minus_mu
    # Prevent overflow: clip values
    x = np.clip(x, -700, 700)
    return 1.0 / (np.exp(x) + 1.0)


def find_mu_bisection(eps, Ne, beta, degeneracy=2, tol=1e-12, maxiter=200):
    """
    Find chemical potential using bisection method.
    
    Parameters:
    -----------
    eps : np.ndarray
        Energy eigenvalues
    Ne : int
        Number of electrons
    beta : float
        Inverse temperature
    degeneracy : int, optional
        Spin degeneracy
    tol : float, optional
        Convergence tolerance
    maxiter : int, optional
        Maximum iterations
        
    Returns:
    --------
    float
        Chemical potential
    """
    T = 1.0 / (beta * kB_ha_per_K)
    # Bracket
    emin, emax = np.min(eps), np.max(eps)
    # Make wide bracket
    left = emin / 2
    right = emax / 2

    def F(mu):
        occ = degeneracy * np.sum(fermi(eps - mu, beta))
        return occ - Ne

    fleft, fright = F(left), F(right)
    if fleft * fright > 0:
        # Try wider bracket
        left, right = emin - 10, emax + 10
        fleft, fright = F(left), F(right)
        if fleft * fright > 0:
            raise RuntimeError("Could not bracket root; check eps/Ne/T or units.")

    for _ in range(maxiter):
        mid = 0.5 * (left + right)
        fmid = F(mid)
        if abs(fmid) < tol:
            return mid
        else:
            print(f"mu (Hartree) = {mid}, F(mu) = {fmid}")
        # Narrow bracket
        if fleft * fmid <= 0:
            right, fright = mid, fmid
        else:
            left, fleft = mid, fmid
    raise RuntimeError("Bisection did not converge within maxiter")


def readVQFromMeta(meta_h5, q, int_path="df_hf_int", ignore_img=False):
    """
    Read VQ from h5 file generated by initialization script.
    
    Parameters:
    -----------
    meta_h5 : str
        Path to metadata HDF5 file
    q : int
        Index of the chunk in VQ_{}
    int_path : str, optional
        Path to integral files
    ignore_img : bool, optional
        Whether to ignore imaginary parts
        
    Returns:
    --------
    tuple
        V_sqr, chunk_start, len_V
    """
    # Find the starting Q index from meta.h5
    chunk_start = h5py.File(meta_h5, "r")["/chunk_indices"][q]
    # Open the file
    V = h5py.File(f"{int_path}/VQ_{chunk_start}.h5", "r")[f"/{chunk_start}"]
    # Find how many aux basis are in the chunk
    len_V = V.shape[1]
    nao = V.shape[2]

    # Pack real and imaginary parts together
    if not ignore_img:
        V_sqr = np.zeros((V.shape[0], len_V, nao, nao), dtype=complex)
        for idx in range(nao):
            V_sqr[:, :, :, idx] = V[:, :, :, idx * 2] + V[:, :, :, idx * 2 + 1] * (0 + 1j)
    else:
        print("Reading without imaginary parts...")
        V_sqr = np.zeros((V.shape[0], len_V, nao, nao), dtype=float)
        for idx in range(nao):
            V_sqr[:, :, :, idx] = V[:, :, :, idx * 2]

    return V_sqr, chunk_start, len_V


def readGtau(sim_h5, iter=-1):
    """
    Read G_tau data from a finished scGW calculation.
    
    Parameters:
    -----------
    sim_h5 : str
        Path to simulation HDF5 file
    iter : int, optional
        Iteration number (-1 for latest)
        
    Returns:
    --------
    np.ndarray
        G_tau data stored as complex numbers
    """
    if iter == -1:
        i = h5py.File(sim_h5, "r")["iter"][()]
    else:
        i = iter
    tag = f"/iter{i}/G_tau/data"

    G_data = h5py.File(sim_h5, "r")[tag][()].view(complex)
    
    print(f"G_tau of iter {i} reading finished.")
    
    return G_data


def eval_G_init_tau(beta=1000, input_h5="input.h5", tau_h5="1e5_120.h5"):
    """
    Read G_tau data from the initial HF/DFT calculation.
    
    Parameters:
    -----------
    beta : float, optional
        Inverse temperature
    input_h5 : str, optional
        Input HDF5 file path
    tau_h5 : str, optional
        Tau grid HDF5 file path
        
    Returns:
    --------
    np.ndarray
        Initial G_tau from HF/DFT
    """
    # G(iw) = [iw + mu - F]^(-1)
    wgrid = h5py.File(tau_h5, "r")["/fermi/wsample"][()]
    nao = h5py.File(input_h5, "r")["/params/nao"][()]
    Ne = h5py.File(input_h5, "r")["/params/nel_cell"][()]
    mo_energy = h5py.File(input_h5, "r")["/HF/mo_energy"][()]
    C = h5py.File(input_h5, "r")["/HF/mo_coeff"][()]

    wgrid = (2 * np.pi / beta) * wgrid  # rescale to Matsubara frequencies
    mu = find_mu_bisection(mo_energy, Ne, beta, degeneracy=2)
    niw = wgrid.shape[0]
    print(f"The chemical potential mu (Hartree) = {mu}")
    
    G_diag = np.zeros((niw, nao), dtype=np.complex128)
    for i, e in enumerate(mo_energy):
        G_diag[:, i] = 1.0 / (wgrid * 1j + mu - e)
    
    G_AO = np.zeros((niw, 1, 1, nao, nao), dtype=np.complex128)  # add spin and k-point dimensions
    for iw in range(niw):
        G_AO[iw] += C @ np.diag(G_diag[iw, :]) @ C.conj().T
    
    G_tau = irFT.omega2tauFTforG(G_AO, beta=beta, tau_h5=tau_h5)
    
    print("G_tau of initial HF/DFT reading finished.")
    
    return G_tau


def eval_P0_tilde_Q_init(NQ, beta=1000,
                         int_path="df_hf_int/",
                         input_h5="input.h5",
                         tau_h5="/home/wenm/irgrids/1e5_136.h5"):
    """
    Calculate P0_tilde with the initial G from HF/DFT.
    
    Parameters:
    -----------
    NQ : int
        Number of auxiliary basis functions
    beta : float, optional
        Inverse temperature
    int_path : str, optional
        Path to integral files
    input_h5 : str, optional
        Input HDF5 file path
    tau_h5 : str, optional
        Tau grid HDF5 file path
        
    Returns:
    --------
    np.ndarray
        Initial P0_tilde
    """
    # Append one point each at the beginning and at the end
    meta_h5 = int_path + "meta.h5"
    num_chunks = len(h5py.File(meta_h5)["/chunk_indices"][()])
    
    G_tau_init = eval_G_init_tau(beta=beta,
                                 input_h5=input_h5,
                                 tau_h5=tau_h5)
    
    num_tau = G_tau_init.shape[0]  # Number of tau points
    num_s = G_tau_init.shape[1]    # Number of spins
    num_k = G_tau_init.shape[2]    # Number of k-points
    nao = G_tau_init.shape[3]      # Number of atomic orbitals
    P0_tilde = np.zeros((num_tau, num_s, num_k, NQ, NQ), dtype=np.complex128)

    print("*****     P0     *****")

    # Loop over half of tau axis
    for t in range(num_tau // 2):
        for s in range(num_s):
            for k in range(num_k):
                tt = num_tau - t - 1  # another index from the end of the tau list
                g1 = G_tau_init[tt, s, k, :, :].reshape(nao, nao)
                g2 = G_tau_init[t, s, k, :, :].reshape(nao, nao)
                for q1 in range(num_chunks):
                    V1, chunk_start1, len_V1 = readVQFromMeta(meta_h5, q1, int_path=int_path)
                    V1_Qa_d = V1.reshape(len_V1 * nao, nao)
                    X1_Qa_c = np.matmul(V1_Qa_d.conjugate(), g1.T)
                    X1_Q_a_c = X1_Qa_c.reshape(len_V1, nao, nao)
                    for q2 in range(num_chunks):
                        V2, chunk_start2, len_V2 = readVQFromMeta(meta_h5, q2, int_path=int_path)
                        V2_b_cQ = V2.transpose([0, 2, 3, 1]).reshape(nao, nao * len_V2)
                        X2_a_cQ = np.matmul(g2, V2_b_cQ)
                        X2_a_c_Q = X2_a_cQ.reshape(nao, nao, len_V2)
                        P0_tilde[t, s, k, chunk_start1:chunk_start1+len_V1, chunk_start2:chunk_start2+len_V2] -= \
                            2 * np.einsum('Qac,acP->QP', X1_Q_a_c, X2_a_c_Q, optimize=True)
                        # The shape of P0_tilde is t * s * k * Qchunk^2 (complex)
                        
    return P0_tilde


def eval_P0_tilde_Q(iter, nao, NQ,
                    int_path="df_hf_int/",
                    sim_h5="scgw/sim.h5"):
    """
    Calculate P0_tilde, but looping over Q.
    
    Parameters:
    -----------
    iter : int
        Iteration number
    nao : int
        Number of atomic orbitals
    NQ : int
        Number of auxiliary basis functions
    int_path : str, optional
        Path to integral files
    sim_h5 : str, optional
        Simulation HDF5 file path
        
    Returns:
    --------
    np.ndarray
        P0_tilde for given iteration
    """
    # Append one point each at the beginning and at the end
    meta_h5 = int_path + "meta.h5"
    num_chunks = len(h5py.File(meta_h5)["/chunk_indices"][()])

    G_tau = readGtau(sim_h5, iter)
    num_tau = G_tau.shape[0]  # Number of tau points
    num_s = G_tau.shape[1]    # Number of spins
    num_k = G_tau.shape[2]    # Number of k-points
    P0_tilde = np.zeros((num_tau, num_s, num_k, NQ, NQ), dtype=np.complex128)

    print("*****     P0     *****")

    # Loop over half of tau axis
    for t in range(num_tau // 2):
        for s in range(num_s):
            for k in range(num_k):
                tt = num_tau - t - 1  # another index from the end of the list
                g1 = G_tau[tt, s, k, :, :].reshape(nao, nao)
                g2 = G_tau[t, s, k, :, :].reshape(nao, nao)
                for q1 in range(num_chunks):
                    V1, chunk_start1, len_V1 = readVQFromMeta(meta_h5, q1, int_path=int_path)
                    V1_Qa_d = V1.reshape(len_V1 * nao, nao)
                    X1_Qa_c = np.matmul(V1_Qa_d.conjugate(), g1.T)
                    X1_Q_ac = X1_Qa_c.reshape(len_V1, nao * nao)
                    for q2 in range(num_chunks):
                        V2, chunk_start2, len_V2 = readVQFromMeta(meta_h5, q2, int_path=int_path)
                        V2_b_cQ = V2.transpose([0, 2, 3, 1]).reshape(nao, nao * len_V2)
                        X2_a_cQ = np.matmul(g2, V2_b_cQ)
                        X2_ac_Q = X2_a_cQ.reshape(nao * nao, len_V2)
                        P0_tilde[t, s, k, chunk_start1:chunk_start1+len_V1, chunk_start2:chunk_start2+len_V2] -= \
                            2 * np.matmul(X1_Q_ac, X2_ac_Q)
                        # The shape of P0_tilde is t * s * k * Qchunk^2 (complex)
                        # times 2 because of spin summation
                        
    return P0_tilde


def symmetrize_P0(P0_tilde):
    """
    Symmetrize P0 using tau symmetry: P0(t) = P0(beta - t).
    
    Parameters:
    -----------
    P0_tilde : np.ndarray
        Input P0_tilde array
        
    Returns:
    --------
    np.ndarray
        Symmetrized P0_tilde
    """
    print("Symmetrizing P0...")
    num_tau = P0_tilde.shape[0]
    num_s = P0_tilde.shape[1]  # Number of spins
    num_k = P0_tilde.shape[2]  # Number of k-points
    
    for t in range(num_tau // 2):
        for s in range(num_s):
            for k in range(num_k):
                # Hermitization
                P0_tilde[t, s, k, :, :] = 0.5 * (P0_tilde[t, s, k, :, :] + 
                                                  P0_tilde[t, s, k, :, :].conjugate().transpose())
                tt = num_tau - t - 1
                P0_tilde[tt, s, k, :, :] += P0_tilde[t, s, k, :, :]

    return P0_tilde


def eval_P_tilde(P0_tilde, beta=1000, tau_h5="~/ir_grids/1e6_168.h5"):
    """
    1) Transform P of tau to frequency axis;
    2) Solve Dyson equation;
    3) Transform back to tau axis.
    
    Parameters:
    -----------
    P0_tilde : np.ndarray
        Input P0_tilde in tau space
    beta : float, optional
        Inverse temperature
    tau_h5 : str, optional
        Tau grid HDF5 file path
        
    Returns:
    --------
    np.ndarray
        P_tilde in tau space
    """
    print("*****    P_tilde    *****")

    NQ = P0_tilde.shape[-1]  # Number of aux points
    fourier = IR_factory(beta, tau_h5)
    # Transform P0(tau) to P0(iw)
    P0_iw = fourier.tauf_to_wb(P0_tilde)
    num_freq = P0_iw.shape[0]  # Find out number of frequency points
    num_s = P0_iw.shape[1]     # Number of spins
    num_k = P0_iw.shape[2]     # Number of k-points
    
    # Solve Dyson eqn: P(iw) = [I-P0(iw)]^(-1)P0(iw)
    P_iw = np.zeros((num_freq, num_s, num_k, NQ, NQ), dtype=np.complex128)
    for iw in range(num_freq):
        for s in range(num_s):
            for k in range(num_k):
                idtt = np.identity(NQ, dtype=np.complex128)  # define identity matrix
                temp = idtt - P0_iw[iw, s, k, :, :]
                temp = inv(temp)  # using inverse function from scipy
                P_iw[iw, s, k, :, :] += np.matmul(temp, P0_iw[iw, s, k, :, :])
    
    P_iw = 0.5 * (P_iw + P_iw.conjugate().transpose([0, 1, 2, 4, 3]))  # Hermitization
            
    # Transform P(iw) to P(tau)
    P_tilde = fourier.wb_to_tauf(P_iw)

    return P_tilde
