#                                                                             #
#    Copyright (c) 2025 Ming Wen <wenm@umich.edu>, University of Michigan.    #
#                                                                             #
#    Functions used for generating intermediagte quantities from GW           # 
#    calcualtions. Reusing them for BSE.                                      #
#                                                                             #


from ir import IR_factory,read_IR_matrices
import h5py
import numpy as np
from scipy.linalg import inv, eigvals


def readVQFromMeta(meta_h5,q,ignore_img=False):
    '''
    Read VQ from h5 file generated by initialization script. 
    q is the index of the chunk in VQ_{}. 
    Reference should be in meta.h5. 
    '''
    # find the starting Q index from meta.h5.
    chunk_start = h5py.File(meta_h5,"r")["/chunk_indices"][q]
    # open the file.
    V = h5py.File("df_hf_int/VQ_{}.h5".format(chunk_start), "r")["/"+str(chunk_start)]
    # find how many aux basis are in the chunk.
    len_V = V.shape[1]
    nao = V.shape[2]

    # pack real and imaginary parts together.
    if not ignore_img:
        V_sqr = np.zeros((V.shape[0],len_V,nao,nao), dtype=complex)
        for idx in range(nao):
            V_sqr[:,:,:,idx] = V[:,:,:,idx*2] + V[:,:,:,idx*2+1] * (0+1j)
    else:
        print("Reading without imaginary parts...")
        V_sqr = np.zeros((V.shape[0],len_V,nao,nao), dtype=float)
        for idx in range(nao):
            V_sqr[:,:,:,idx] = V[:,:,:,idx*2]

    # print("Chunk number {} reading finished, starting at index {}".format(q, chunk_start))
    return V_sqr, chunk_start, len_V


def readGtau(sim_h5):
    '''
    Read G_tau data from a finished scGW calculation.
    Dimensions are (1+n_tau+1) * n_spin * ink * nao * nao * 2,
    Stored as complex numbers.
    i is the index of iteration. 
    '''

    i = h5py.File(sim_h5, "r")["iter"][()]
    tag = "/iter{}/G_tau/data".format(i)

    G_data = h5py.File(sim_h5, "r")[tag][()].view(complex)
    
    print("G_tau of iter {} reading finished.".format(i))
    
    return G_tau


def eval_P0_tilde_Q(meta_h5 ="df_hf_int/meta.h5", \
                    input_h5="input.h5", \
                    sim_h5  ="scgw/sim.h5"):
    '''
    Calculate P0_tilde, but looping over Q
    '''
    # append one point each at the beginning and at the end.

    num_chunks = len(h5py.File(meta_h5)["/chunk_indices"][()])

    G_tau   = readGtau(sim_h5)
    num_tau = G_tau.shape[0]  # Number of tau points
    num_s   = G_tau.shape[1]  # Number of spins
    num_k   = G_tau.shape[2]  # Number of k-points
    NQ      = int(h5py.File(tau_h5,"r")["/params/NQ"])  # Number of aux points
    P0_tilde = np.zeros((num_tau,num_s,num_k,NQ,NQ), dtype=np.complex128)  

    print("*****     P0     *****")

    # loop over half of tau axis.
    for t in range(num_tau//2):
        for s in range(num_s):
            for k in range(num_k):
                # print("----- tau index = {} -----".format(t))
                tt = num_tau - t - 1 # another index from the end of the list.
                g1 = G_tau[tt,s,k,:,:].reshape(nao,nao)
                g2 = G_tau[t,s,k,:,:].reshape(nao,nao)
                for q1 in range(num_chunks):
                    V1, chunk_start1, len_V1 = readVQFromMeta(meta_h5,q1) 
                    V1_Qa_d = V1.reshape(len_V1*nao,nao)
                    X1_Qa_c = np.matmul(V1_Qa_d.conjugate(),g1.T)
                    X1_Q_ac = X1_Qa_c.reshape(len_V1,nao*nao)
                    for q2 in range(num_chunks): 
                        # print("Filling chunk [{},{}] ...".format(q1,q2))
                        V2, chunk_start2, len_V2 = readVQFromMeta(meta_h5,q2) 
                        V2_b_cQ = V2.transpose([0,2,3,1]).reshape(nao,nao*len_V2)
                        X2_a_cQ = np.matmul(g2, V2_b_cQ)
                        X2_ac_Q = X2_a_cQ.reshape(nao*nao,len_V2)
                        P0_tilde[t,s,k,chunk_start1:chunk_start1+len_V1,chunk_start2:chunk_start2+len_V2] -= \
                            2 * np.matmul(X1_Q_ac,X2_ac_Q)
                        # The shape of P0_tilde is t * s * k * Qchunk^2 (complex).
                        
    return P0_tilde


# def symmetrize_P0(P0_tilde, tau_h5="~/ir_grids/1e6_168.h5"):
def symmetrize_P0(P0_tilde):
    '''
        for (size_t it = t_start; it < t_end; ++it) { // Symmetry of tau: P0(t) = P0(beta - t)
      _P0_tilde(_nts - it - 1, 0).matrix() = _P0_tilde(it, 0).matrix();
    }
    '''
    print("Symmetrizing P0...")
    num_tau = P0_tilde.shape[0]
    num_s   = P0_tilde.shape[1]  # Number of spins
    num_k   = P0_tilde.shape[2]  # Number of k-points
    for t in range(num_tau//2):
        for s in range(num_s):
            for k in range(num_k):
                # Hermitization
                P0_tilde[t,s,k,:,:] = 0.5 * (P0_tilde[t,s,k,:,:] + P0_tilde[t,s,k,:,:].conjugate().transpose())
                tt = num_tau - t - 1
                P0_tilde[tt,s,k,:,:] = P0_tilde[t,s,k,:,:]

    return P0_tilde


# def eval_P_tilde(P0_tilde, NQ, beta = 1000, tau_h5="~/ir_grids/1e6_168.h5"):
def eval_P_tilde(P0_tilde, beta = 1000, tau_h5="~/ir_grids/1e6_168.h5"):
    '''
    1) Transform P of tau to frequency axis;
    2) Solve Dyson equation;
    3) Transform back to tau axis.
    '''

    print("*****    P_tilde    *****")

    NQ = P0_tilde.shape0[-1]  # Number of aux points. 
    fourier = IR_factory(beta, tau_h5)
    # transform P0(tau) to P0(iw).
    P0_iw   = fourier.tauf_to_wb(P0_tilde)
    num_freq  = P0_iw.shape[0] # find out number of frequency points.
    num_s   = P0_iw.shape[1]  # Number of spins
    num_k   = P0_iw.shape[2]  # Number of k-points
    
    # solve Dyson eqn: P(iw) = [I-P0(iw)]^(-1)P0(iw)
    P_iw = np.zeros((num_freq,num_s,num_k,NQ,NQ), dtype=np.complex128)
    for iw in range(num_freq):
        for s in range(num_s):
            for k in range(num_k):
                idtt = np.identity(NQ, dtype=np.complex128)  # define identity matrix.
                temp = idtt - P0_iw[iw,s,k,:,:]
                temp = inv(temp)  # using inverse function from scipy. 
                temp = 0.5 * (temp + temp.conjugate().transpose())  # Hermitization
                P_iw[iw,s,k,:,:] += np.matmul(temp, P0_iw[iw,s,k,:,:])
            
    # transform P(iw) to P(tau).
    P_tilde = fourier.wb_to_tauf(P_iw)

    return P_tilde
